import {
  addColumns,
  createTable,
  schemaMigrations,
  unsafeExecuteSql,
} from "@nozbe/watermelondb/Schema/migrations";
import {
  BACKFILL_EMPTY_BILLING_DOCUMENT_NUMBER_SQL,
  BILLING_DOCUMENT_ACTIVE_NUMBER_UNIQUE_INDEX_SQL,
  DEDUPE_ACTIVE_BILLING_DOCUMENT_NUMBER_SQL,
  NORMALIZE_BILLING_DOCUMENT_NUMBER_SQL,
} from "@/feature/billing/data/dataSource/db/billingDocument.uniqueIndex";

export const migrations = schemaMigrations({
  migrations: [
    {
      toVersion: 11,
      steps: [
        createTable({
          name: "auth_credentials",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            { name: "user_remote_id", type: "string", isIndexed: true },
            { name: "login_id", type: "string", isIndexed: true },
            { name: "credential_type", type: "string", isIndexed: true },
            { name: "password_hash", type: "string" },
            { name: "password_salt", type: "string" },
            { name: "hint", type: "string", isOptional: true },
            { name: "last_login_at", type: "number", isOptional: true },
            { name: "is_active", type: "boolean" },
            { name: "sync_status", type: "string", isIndexed: true },
            { name: "last_synced_at", type: "number", isOptional: true },
            { name: "deleted_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
      ],
    },
    {
      toVersion: 12,
      steps: [
        addColumns({
          table: "auth_credentials",
          columns: [
            { name: "failed_attempt_count", type: "number", isOptional: true },
            { name: "lockout_until", type: "number", isOptional: true },
            { name: "last_failed_login_at", type: "number", isOptional: true },
          ],
        }),
        createTable({
          name: "app_settings",
          columns: [
            { name: "selected_language", type: "string" },
            { name: "onboarding_completed", type: "boolean" },
            {
              name: "active_user_remote_id",
              type: "string",
              isOptional: true,
              isIndexed: true,
            },
            {
              name: "active_account_remote_id",
              type: "string",
              isOptional: true,
              isIndexed: true,
            },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
      ],
    },
    {
      toVersion: 13,
      steps: [
        createTable({
          name: "accounts",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            { name: "owner_user_remote_id", type: "string", isIndexed: true },
            { name: "account_type", type: "string", isIndexed: true },
            { name: "display_name", type: "string" },
            { name: "currency_code", type: "string", isOptional: true },
            { name: "city_or_location", type: "string", isOptional: true },
            { name: "country_code", type: "string", isOptional: true },
            { name: "is_active", type: "boolean" },
            { name: "is_default", type: "boolean" },
            { name: "sync_status", type: "string", isIndexed: true },
            { name: "last_synced_at", type: "number", isOptional: true },
            { name: "deleted_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
      ],
    },
    {
      toVersion: 14,
      steps: [
        addColumns({
          table: "accounts",
          columns: [
            { name: "business_type", type: "string", isOptional: true },
          ],
        }),
      ],
    },
    {
      toVersion: 15,
      steps: [
        createTable({
          name: "business_profiles",
          columns: [
            { name: "account_remote_id", type: "string", isIndexed: true },
            { name: "owner_user_remote_id", type: "string", isIndexed: true },
            { name: "business_type", type: "string" },
            { name: "business_name", type: "string" },
            { name: "country_code", type: "string" },
            { name: "currency_code", type: "string" },
            { name: "timezone", type: "string" },
            { name: "phone_policy", type: "string" },
            { name: "is_active", type: "boolean" },
            { name: "sync_status", type: "string", isIndexed: true },
            { name: "last_synced_at", type: "number", isOptional: true },
            { name: "deleted_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
      ],
    },
    {
      toVersion: 16,
      steps: [
        addColumns({
          table: "business_profiles",
          columns: [
            { name: "business_logo_url", type: "string", isOptional: true },
            { name: "business_phone", type: "string", isOptional: true },
            { name: "business_email", type: "string", isOptional: true },
            { name: "registered_address", type: "string", isOptional: true },
            { name: "country", type: "string", isOptional: true },
            { name: "city", type: "string", isOptional: true },
            { name: "state_or_district", type: "string", isOptional: true },
            { name: "tax_registration_id", type: "string", isOptional: true },
          ],
        }),
      ],
    },
    {
      toVersion: 17,
      steps: [
        createTable({
          name: "user_management_permissions",
          columns: [
            { name: "code", type: "string", isIndexed: true },
            { name: "module", type: "string", isIndexed: true },
            { name: "label", type: "string" },
            { name: "description", type: "string" },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
        createTable({
          name: "account_roles",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            { name: "account_remote_id", type: "string", isIndexed: true },
            { name: "name", type: "string" },
            { name: "is_system", type: "boolean" },
            { name: "is_default", type: "boolean" },
            { name: "sync_status", type: "string", isIndexed: true },
            { name: "last_synced_at", type: "number", isOptional: true },
            { name: "deleted_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
        createTable({
          name: "account_role_permissions",
          columns: [
            { name: "role_remote_id", type: "string", isIndexed: true },
            { name: "permission_code", type: "string", isIndexed: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
        createTable({
          name: "account_user_roles",
          columns: [
            { name: "account_remote_id", type: "string", isIndexed: true },
            { name: "user_remote_id", type: "string", isIndexed: true },
            { name: "role_remote_id", type: "string", isIndexed: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
      ],
    },
    {
      toVersion: 18,
      steps: [
        createTable({
          name: "account_members",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            { name: "account_remote_id", type: "string", isIndexed: true },
            { name: "user_remote_id", type: "string", isIndexed: true },
            { name: "status", type: "string", isIndexed: true },
            {
              name: "invited_by_user_remote_id",
              type: "string",
              isOptional: true,
            },
            { name: "joined_at", type: "number", isOptional: true },
            { name: "last_active_at", type: "number", isOptional: true },
            { name: "sync_status", type: "string", isIndexed: true },
            { name: "last_synced_at", type: "number", isOptional: true },
            { name: "deleted_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
      ],
    },
    {
      toVersion: 19,
      steps: [
        createTable({
          name: "transactions",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            { name: "owner_user_remote_id", type: "string", isIndexed: true },
            { name: "account_remote_id", type: "string", isIndexed: true },
            { name: "account_display_name_snapshot", type: "string" },
            { name: "transaction_type", type: "string", isIndexed: true },
            { name: "direction", type: "string", isIndexed: true },
            { name: "title", type: "string" },
            { name: "amount", type: "number" },
            { name: "currency_code", type: "string", isOptional: true },
            { name: "category_label", type: "string", isOptional: true },
            { name: "note", type: "string", isOptional: true },
            { name: "happened_at", type: "number", isIndexed: true },
            { name: "sync_status", type: "string", isIndexed: true },
            { name: "last_synced_at", type: "number", isOptional: true },
            { name: "deleted_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
      ],
    },
    {
      toVersion: 20,
      steps: [
        createTable({
          name: "ledger_entries",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            {
              name: "business_account_remote_id",
              type: "string",
              isIndexed: true,
            },
            { name: "owner_user_remote_id", type: "string", isIndexed: true },
            { name: "party_name", type: "string", isIndexed: true },
            { name: "party_phone", type: "string", isOptional: true },
            { name: "entry_type", type: "string", isIndexed: true },
            { name: "balance_direction", type: "string", isIndexed: true },
            { name: "title", type: "string" },
            { name: "amount", type: "number" },
            { name: "currency_code", type: "string", isOptional: true },
            { name: "note", type: "string", isOptional: true },
            { name: "happened_at", type: "number", isIndexed: true },
            {
              name: "due_at",
              type: "number",
              isOptional: true,
              isIndexed: true,
            },
            {
              name: "settlement_account_remote_id",
              type: "string",
              isOptional: true,
              isIndexed: true,
            },
            {
              name: "settlement_account_display_name_snapshot",
              type: "string",
              isOptional: true,
            },
            { name: "sync_status", type: "string", isIndexed: true },
            { name: "last_synced_at", type: "number", isOptional: true },
            { name: "deleted_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
      ],
    },
    {
      toVersion: 21,
      steps: [
        createTable({
          name: "emi_plans",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            { name: "owner_user_remote_id", type: "string", isIndexed: true },
            {
              name: "business_account_remote_id",
              type: "string",
              isOptional: true,
              isIndexed: true,
            },
            { name: "plan_mode", type: "string", isIndexed: true },
            { name: "plan_type", type: "string", isIndexed: true },
            { name: "payment_direction", type: "string", isIndexed: true },
            { name: "title", type: "string" },
            {
              name: "counterparty_name",
              type: "string",
              isOptional: true,
              isIndexed: true,
            },
            { name: "counterparty_phone", type: "string", isOptional: true },
            {
              name: "linked_account_remote_id",
              type: "string",
              isIndexed: true,
            },
            { name: "linked_account_display_name_snapshot", type: "string" },
            { name: "currency_code", type: "string", isOptional: true },
            { name: "total_amount", type: "number" },
            { name: "installment_count", type: "number" },
            { name: "paid_installment_count", type: "number" },
            { name: "paid_amount", type: "number" },
            { name: "first_due_at", type: "number", isIndexed: true },
            {
              name: "next_due_at",
              type: "number",
              isOptional: true,
              isIndexed: true,
            },
            { name: "reminder_enabled", type: "boolean" },
            { name: "reminder_days_before", type: "number", isOptional: true },
            { name: "note", type: "string", isOptional: true },
            { name: "status", type: "string", isIndexed: true },
            { name: "sync_status", type: "string", isIndexed: true },
            { name: "last_synced_at", type: "number", isOptional: true },
            { name: "deleted_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
        createTable({
          name: "emi_installments",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            { name: "plan_remote_id", type: "string", isIndexed: true },
            { name: "installment_number", type: "number", isIndexed: true },
            { name: "amount", type: "number" },
            { name: "due_at", type: "number", isIndexed: true },
            { name: "status", type: "string", isIndexed: true },
            { name: "paid_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
        createTable({
          name: "installment_payment_links",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            { name: "plan_remote_id", type: "string", isIndexed: true },
            { name: "installment_remote_id", type: "string", isIndexed: true },
            { name: "payment_record_type", type: "string", isIndexed: true },
            {
              name: "payment_record_remote_id",
              type: "string",
              isIndexed: true,
            },
            { name: "payment_direction", type: "string", isIndexed: true },
            { name: "amount", type: "number" },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
      ],
    },
    {
      toVersion: 22,
      steps: [
        createTable({
          name: "inventory_movements",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            { name: "account_remote_id", type: "string", isIndexed: true },
            { name: "product_remote_id", type: "string", isIndexed: true },
            { name: "product_name_snapshot", type: "string" },
            {
              name: "product_unit_label_snapshot",
              type: "string",
              isOptional: true,
            },
            { name: "movement_type", type: "string", isIndexed: true },
            { name: "quantity", type: "number" },
            { name: "delta_quantity", type: "number" },
            { name: "unit_rate", type: "number", isOptional: true },
            { name: "reason", type: "string", isOptional: true },
            { name: "remark", type: "string", isOptional: true },
            { name: "movement_at", type: "number", isIndexed: true },
            { name: "sync_status", type: "string", isIndexed: true },
            { name: "last_synced_at", type: "number", isOptional: true },
            { name: "deleted_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
        createTable({
          name: "products",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            { name: "account_remote_id", type: "string", isIndexed: true },
            { name: "name", type: "string", isIndexed: true },
            { name: "kind", type: "string", isIndexed: true },
            { name: "category_name", type: "string", isOptional: true },
            { name: "sale_price", type: "number" },
            { name: "cost_price", type: "number", isOptional: true },
            { name: "stock_quantity", type: "number", isOptional: true },
            { name: "unit_label", type: "string", isOptional: true },
            { name: "sku_or_barcode", type: "string", isOptional: true },
            { name: "tax_rate_label", type: "string", isOptional: true },
            { name: "description", type: "string", isOptional: true },
            { name: "image_url", type: "string", isOptional: true },
            { name: "status", type: "string", isIndexed: true },
            { name: "sync_status", type: "string", isIndexed: true },
            { name: "last_synced_at", type: "number", isOptional: true },
            { name: "deleted_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
      ],
    },
    {
      toVersion: 23,
      steps: [
        createTable({
          name: "categories",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            { name: "owner_user_remote_id", type: "string", isIndexed: true },
            { name: "account_remote_id", type: "string", isIndexed: true },
            { name: "account_type", type: "string", isIndexed: true },
            { name: "scope", type: "string", isIndexed: true },
            { name: "kind", type: "string", isIndexed: true },
            { name: "name", type: "string", isIndexed: true },
            { name: "description", type: "string", isOptional: true },
            { name: "is_system", type: "boolean", isIndexed: true },
            { name: "sync_status", type: "string", isIndexed: true },
            { name: "last_synced_at", type: "number", isOptional: true },
            { name: "deleted_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
      ],
    },
    {
      toVersion: 24,
      steps: [
        createTable({
          name: "money_accounts",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            { name: "owner_user_remote_id", type: "string", isIndexed: true },
            {
              name: "scope_account_remote_id",
              type: "string",
              isIndexed: true,
            },
            { name: "name", type: "string" },
            { name: "account_type", type: "string", isIndexed: true },
            { name: "current_balance", type: "number" },
            { name: "description", type: "string", isOptional: true },
            { name: "currency_code", type: "string", isOptional: true },
            { name: "is_primary", type: "boolean" },
            { name: "is_active", type: "boolean" },
            { name: "sync_status", type: "string", isIndexed: true },
            { name: "last_synced_at", type: "number", isOptional: true },
            { name: "deleted_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
        createTable({
          name: "contacts",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            { name: "owner_user_remote_id", type: "string", isIndexed: true },
            { name: "account_remote_id", type: "string", isIndexed: true },
            { name: "account_type", type: "string", isIndexed: true },
            { name: "contact_type", type: "string", isIndexed: true },
            { name: "full_name", type: "string", isIndexed: true },
            { name: "phone_number", type: "string", isOptional: true },
            { name: "email_address", type: "string", isOptional: true },
            { name: "address", type: "string", isOptional: true },
            { name: "tax_id", type: "string", isOptional: true },
            { name: "opening_balance_amount", type: "number" },
            {
              name: "opening_balance_direction",
              type: "string",
              isOptional: true,
            },
            { name: "notes", type: "string", isOptional: true },
            { name: "is_archived", type: "boolean", isIndexed: true },
            { name: "sync_status", type: "string", isIndexed: true },
            { name: "last_synced_at", type: "number", isOptional: true },
            { name: "deleted_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
        createTable({
          name: "billing_documents",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            { name: "account_remote_id", type: "string", isIndexed: true },
            { name: "document_number", type: "string", isIndexed: true },
            { name: "document_type", type: "string", isIndexed: true },
            { name: "template_type", type: "string", isIndexed: true },
            { name: "customer_name", type: "string" },
            { name: "status", type: "string", isIndexed: true },
            { name: "tax_rate_percent", type: "number" },
            { name: "notes", type: "string", isOptional: true },
            { name: "subtotal_amount", type: "number" },
            { name: "tax_amount", type: "number" },
            { name: "total_amount", type: "number" },
            { name: "issued_at", type: "number", isIndexed: true },
            { name: "sync_status", type: "string", isIndexed: true },
            { name: "last_synced_at", type: "number", isOptional: true },
            { name: "deleted_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
        createTable({
          name: "billing_document_items",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            { name: "document_remote_id", type: "string", isIndexed: true },
            { name: "line_order", type: "number" },
            { name: "item_name", type: "string" },
            { name: "quantity", type: "number" },
            { name: "unit_rate", type: "number" },
            { name: "line_total", type: "number" },
            { name: "deleted_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
        createTable({
          name: "bill_photos",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            { name: "account_remote_id", type: "string", isIndexed: true },
            {
              name: "document_remote_id",
              type: "string",
              isOptional: true,
              isIndexed: true,
            },
            { name: "file_name", type: "string" },
            { name: "mime_type", type: "string", isOptional: true },
            { name: "image_data_url", type: "string" },
            { name: "uploaded_at", type: "number", isIndexed: true },
            { name: "sync_status", type: "string", isIndexed: true },
            { name: "last_synced_at", type: "number", isOptional: true },
            { name: "deleted_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
        createTable({
          name: "business_notes",
          columns: [
            { name: "account_remote_id", type: "string", isIndexed: true },
            { name: "note_content", type: "string", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
      ],
    },
    {
      toVersion: 25,
      steps: [
        unsafeExecuteSql(NORMALIZE_BILLING_DOCUMENT_NUMBER_SQL),
        unsafeExecuteSql(BACKFILL_EMPTY_BILLING_DOCUMENT_NUMBER_SQL),
        unsafeExecuteSql(DEDUPE_ACTIVE_BILLING_DOCUMENT_NUMBER_SQL),
        unsafeExecuteSql(BILLING_DOCUMENT_ACTIVE_NUMBER_UNIQUE_INDEX_SQL),
      ],
    },
    {
      toVersion: 26,
      steps: [
        createTable({
          name: "orders",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            { name: "owner_user_remote_id", type: "string", isIndexed: true },
            { name: "account_remote_id", type: "string", isIndexed: true },
            { name: "order_number", type: "string", isIndexed: true },
            { name: "order_date", type: "number", isIndexed: true },
            {
              name: "customer_remote_id",
              type: "string",
              isOptional: true,
              isIndexed: true,
            },
            {
              name: "delivery_or_pickup_details",
              type: "string",
              isOptional: true,
            },
            { name: "notes", type: "string", isOptional: true },
            { name: "tags", type: "string", isOptional: true },
            { name: "internal_remarks", type: "string", isOptional: true },
            { name: "status", type: "string", isIndexed: true },
            { name: "sync_status", type: "string", isIndexed: true },
            { name: "last_synced_at", type: "number", isOptional: true },
            { name: "deleted_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
        createTable({
          name: "order_lines",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            { name: "order_remote_id", type: "string", isIndexed: true },
            { name: "product_remote_id", type: "string", isIndexed: true },
            { name: "quantity", type: "number" },
            { name: "line_order", type: "number", isIndexed: true },
            { name: "sync_status", type: "string", isIndexed: true },
            { name: "last_synced_at", type: "number", isOptional: true },
            { name: "deleted_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
      ],
    },
    {
      toVersion: 27,
      steps: [
        createTable({
          name: "budget_plans",
          columns: [
            { name: "remote_id", type: "string", isIndexed: true },
            { name: "owner_user_remote_id", type: "string", isIndexed: true },
            { name: "account_remote_id", type: "string", isIndexed: true },
            { name: "budget_month", type: "string", isIndexed: true },
            { name: "category_remote_id", type: "string", isIndexed: true },
            { name: "category_name_snapshot", type: "string" },
            { name: "currency_code", type: "string", isOptional: true },
            { name: "planned_amount", type: "number" },
            { name: "note", type: "string", isOptional: true },
            { name: "sync_status", type: "string", isIndexed: true },
            { name: "last_synced_at", type: "number", isOptional: true },
            { name: "deleted_at", type: "number", isOptional: true },
            { name: "created_at", type: "number" },
            { name: "updated_at", type: "number" },
          ],
        }),
      ],
    },
  ],
});
