import { GetMoneyAccountsUseCase } from "@/feature/accounts/useCase/getMoneyAccounts.useCase";
import { GetContactsUseCase } from "@/feature/contacts/useCase/getContacts.useCase";
import { AssignOrderCustomerUseCase } from "@/feature/orders/useCase/assignOrderCustomer.useCase";
import { CancelOrderUseCase } from "@/feature/orders/useCase/cancelOrder.useCase";
import { ChangeOrderStatusUseCase } from "@/feature/orders/useCase/changeOrderStatus.useCase";
import { CreateOrderUseCase } from "@/feature/orders/useCase/createOrder.useCase";
import { DeleteOrderUseCase } from "@/feature/orders/useCase/deleteOrder.useCase";
import { GetOrderByIdUseCase } from "@/feature/orders/useCase/getOrderById.useCase";
import { GetOrdersUseCase } from "@/feature/orders/useCase/getOrders.useCase";
import { GetOrderSettlementSnapshotsUseCase } from "@/feature/orders/useCase/getOrderSettlementSnapshots.useCase";
import { RecordOrderPaymentUseCase } from "@/feature/orders/useCase/recordOrderPayment.useCase";
import { RefundOrderUseCase } from "@/feature/orders/useCase/refundOrder.useCase";
import { RemoveOrderItemUseCase } from "@/feature/orders/useCase/removeOrderItem.useCase";
import { ReturnOrderUseCase } from "@/feature/orders/useCase/returnOrder.useCase";
import { UpdateOrderUseCase } from "@/feature/orders/useCase/updateOrder.useCase";
import { GetProductsUseCase } from "@/feature/products/useCase/getProducts.useCase";

export type OrdersCoordinatorViewModelParams = {
  accountRemoteId: string | null;
  ownerUserRemoteId: string | null;
  accountDisplayNameSnapshot: string;
  accountCurrencyCode: string | null;
  accountCountryCode: string | null;
  accountDefaultTaxRatePercent: number | null;
  canManage: boolean;
  getOrdersUseCase: GetOrdersUseCase;
  getOrderByIdUseCase: GetOrderByIdUseCase;
  createOrderUseCase: CreateOrderUseCase;
  updateOrderUseCase: UpdateOrderUseCase;
  deleteOrderUseCase: DeleteOrderUseCase;
  changeOrderStatusUseCase: ChangeOrderStatusUseCase;
  cancelOrderUseCase: CancelOrderUseCase;
  returnOrderUseCase: ReturnOrderUseCase;
  recordOrderPaymentUseCase: RecordOrderPaymentUseCase;
  refundOrderUseCase: RefundOrderUseCase;
  getContactsUseCase: GetContactsUseCase;
  getProductsUseCase: GetProductsUseCase;
  getMoneyAccountsUseCase: GetMoneyAccountsUseCase;
  getOrderSettlementSnapshotsUseCase: GetOrderSettlementSnapshotsUseCase;
  assignOrderCustomerUseCase: AssignOrderCustomerUseCase;
  removeOrderItemUseCase: RemoveOrderItemUseCase;
};
